import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#acb3b8",
        "primary-fixed-dim": "#d6d3d6",
        "on-secondary": "#faf8fc",
        "secondary-fixed-dim": "#d6d4d7",
        "on-primary": "#faf7f9",
        "error-container": "#fe8983",
        "primary-container": "#e4e2e4",
        "surface-variant": "#dde3e9",
        "on-tertiary-fixed-variant": "#00214a",
        "secondary-container": "#e4e2e5",
        "on-tertiary": "#f8f8ff",
        "on-primary-fixed": "#3f3f41",
        "on-primary-fixed-variant": "#5c5b5d",
        outline: "#757c81",
        primary: "#5f5e60",
        "surface-bright": "#f9f9fb",
        background: "#f9f9fb",
        "tertiary-fixed-dim": "#4088f0",
        surface: "#f9f9fb",
        "secondary-fixed": "#e4e2e5",
        "surface-tint": "#5f5e60",
        "inverse-primary": "#ffffff",
        "surface-container-highest": "#dde3e9",
        tertiary: "#005dbb",
        "surface-container-high": "#e4e9ee",
        "surface-container-low": "#f2f4f6",
        "inverse-surface": "#0c0e10",
        "on-error-container": "#752121",
        "surface-container": "#ebeef2",
        "error-dim": "#4e0309",
        "tertiary-container": "#5095fe",
        "secondary-dim": "#535356",
        "on-error": "#fff7f6",
        "primary-fixed": "#e4e2e4",
        "on-surface": "#2d3338",
        "on-tertiary-container": "#001636",
        "inverse-on-surface": "#9c9d9f",
        "on-secondary-fixed": "#3f3f42",
        error: "#9f403d",
        "surface-dim": "#d3dbe2",
        "tertiary-fixed": "#5095fe",
        "on-background": "#2d3338",
        secondary: "#5f5f62",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#596065",
        "on-secondary-container": "#525154",
        "on-secondary-fixed-variant": "#5b5b5e",
        "on-tertiary-fixed": "#000000",
        "tertiary-dim": "#0051a5",
        "primary-dim": "#535254",
        "on-primary-container": "#525154",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
        sans: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
} satisfies Config;
